# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: nhl-serving:latest
    networks:
      - nhl-network
    ports:
      - 8080:8080
    environment:
      COMET_API_KEY: ${COMET_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: nhl-streamlit:latest
    networks:
      - nhl-network
    ports:
      - 8501:8501
    environment:
      COMET_API_KEY: ${COMET_API_KEY}
networks:
  nhl-network:


