FROM python:3.7
ADD ./ift6758 ./ift6758
ADD ./serving ./serving
ADD ./requirements-stream.txt ./requirements-stream.txt
COPY streamlit_app.py streamlit_app.py
RUN pip install -r requirements-stream.txt
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run" ]
CMD [ "streamlit_app.py", "--server.headless", "true", "--server.port=8501", "--server.address=0.0.0.0", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false"]
