FROM python:3.7
ENV COMET_API_KEY ${COMET_API_KEY}
ADD ./ift6758 ./ift6758
ADD ./serving ./serving
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 8080
#CMD ["gunicorn"  , "--bind", "0.0.0.0:8080", "app:app"]
ENTRYPOINT [ "python3" ]
CMD ["serving/app.py"]